import { EmpresasService } from './empresas.service';
import { Prisma } from '@prisma/client';
export declare class EmpresasController {
    private readonly empresasService;
    constructor(empresasService: EmpresasService);
    create(createEmpresaDto: Prisma.EmpresaCreateInput): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        cpf: string | null;
        email: string | null;
        telefone: string | null;
        ativo: boolean;
        cidade: string | null;
        codigo: string | null;
        estado: string | null;
        cnpj: string | null;
        bairro: string | null;
        cep: string | null;
        complemento: string | null;
        inscricaoEstadual: string | null;
        logradouro: string | null;
        nomeFantasia: string | null;
        numero: string | null;
        razaoSocial: string;
        site: string | null;
        ignorarCaixaFinanceiro: boolean;
        ignorarEstoque: boolean;
        cfop: string | null;
        inscricaoMunicipal: string | null;
        cei: string | null;
        cnaeFiscal: string | null;
        correspondenciaLogradouro: string | null;
        correspondenciaNumero: string | null;
        correspondenciaBairro: string | null;
        correspondenciaEstado: string | null;
        correspondenciaCidade: string | null;
        correspondenciaCep: string | null;
        lotacaoTributaria: string | null;
        codigoFpas: string | null;
        codigoGps: string | null;
        outrasEntidades: string | null;
        codigoFap: string | null;
        codigoSimples: string | null;
        aliquotaRat: number | null;
    }>;
    findAll(): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        cpf: string | null;
        email: string | null;
        telefone: string | null;
        ativo: boolean;
        cidade: string | null;
        codigo: string | null;
        estado: string | null;
        cnpj: string | null;
        bairro: string | null;
        cep: string | null;
        complemento: string | null;
        inscricaoEstadual: string | null;
        logradouro: string | null;
        nomeFantasia: string | null;
        numero: string | null;
        razaoSocial: string;
        site: string | null;
        ignorarCaixaFinanceiro: boolean;
        ignorarEstoque: boolean;
        cfop: string | null;
        inscricaoMunicipal: string | null;
        cei: string | null;
        cnaeFiscal: string | null;
        correspondenciaLogradouro: string | null;
        correspondenciaNumero: string | null;
        correspondenciaBairro: string | null;
        correspondenciaEstado: string | null;
        correspondenciaCidade: string | null;
        correspondenciaCep: string | null;
        lotacaoTributaria: string | null;
        codigoFpas: string | null;
        codigoGps: string | null;
        outrasEntidades: string | null;
        codigoFap: string | null;
        codigoSimples: string | null;
        aliquotaRat: number | null;
    }[]>;
    findOne(id: string): Promise<({
        fazendas: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            nome: string;
            empresaId: string;
            areaProdutiva: number | null;
            areaTotal: number | null;
            cidade: string | null;
            codigo: string | null;
            estado: string | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        cpf: string | null;
        email: string | null;
        telefone: string | null;
        ativo: boolean;
        cidade: string | null;
        codigo: string | null;
        estado: string | null;
        cnpj: string | null;
        bairro: string | null;
        cep: string | null;
        complemento: string | null;
        inscricaoEstadual: string | null;
        logradouro: string | null;
        nomeFantasia: string | null;
        numero: string | null;
        razaoSocial: string;
        site: string | null;
        ignorarCaixaFinanceiro: boolean;
        ignorarEstoque: boolean;
        cfop: string | null;
        inscricaoMunicipal: string | null;
        cei: string | null;
        cnaeFiscal: string | null;
        correspondenciaLogradouro: string | null;
        correspondenciaNumero: string | null;
        correspondenciaBairro: string | null;
        correspondenciaEstado: string | null;
        correspondenciaCidade: string | null;
        correspondenciaCep: string | null;
        lotacaoTributaria: string | null;
        codigoFpas: string | null;
        codigoGps: string | null;
        outrasEntidades: string | null;
        codigoFap: string | null;
        codigoSimples: string | null;
        aliquotaRat: number | null;
    }) | null>;
    update(id: string, updateEmpresaDto: Prisma.EmpresaUpdateInput): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        cpf: string | null;
        email: string | null;
        telefone: string | null;
        ativo: boolean;
        cidade: string | null;
        codigo: string | null;
        estado: string | null;
        cnpj: string | null;
        bairro: string | null;
        cep: string | null;
        complemento: string | null;
        inscricaoEstadual: string | null;
        logradouro: string | null;
        nomeFantasia: string | null;
        numero: string | null;
        razaoSocial: string;
        site: string | null;
        ignorarCaixaFinanceiro: boolean;
        ignorarEstoque: boolean;
        cfop: string | null;
        inscricaoMunicipal: string | null;
        cei: string | null;
        cnaeFiscal: string | null;
        correspondenciaLogradouro: string | null;
        correspondenciaNumero: string | null;
        correspondenciaBairro: string | null;
        correspondenciaEstado: string | null;
        correspondenciaCidade: string | null;
        correspondenciaCep: string | null;
        lotacaoTributaria: string | null;
        codigoFpas: string | null;
        codigoGps: string | null;
        outrasEntidades: string | null;
        codigoFap: string | null;
        codigoSimples: string | null;
        aliquotaRat: number | null;
    }>;
    remove(id: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        cpf: string | null;
        email: string | null;
        telefone: string | null;
        ativo: boolean;
        cidade: string | null;
        codigo: string | null;
        estado: string | null;
        cnpj: string | null;
        bairro: string | null;
        cep: string | null;
        complemento: string | null;
        inscricaoEstadual: string | null;
        logradouro: string | null;
        nomeFantasia: string | null;
        numero: string | null;
        razaoSocial: string;
        site: string | null;
        ignorarCaixaFinanceiro: boolean;
        ignorarEstoque: boolean;
        cfop: string | null;
        inscricaoMunicipal: string | null;
        cei: string | null;
        cnaeFiscal: string | null;
        correspondenciaLogradouro: string | null;
        correspondenciaNumero: string | null;
        correspondenciaBairro: string | null;
        correspondenciaEstado: string | null;
        correspondenciaCidade: string | null;
        correspondenciaCep: string | null;
        lotacaoTributaria: string | null;
        codigoFpas: string | null;
        codigoGps: string | null;
        outrasEntidades: string | null;
        codigoFap: string | null;
        codigoSimples: string | null;
        aliquotaRat: number | null;
    }>;
}
